export const supabaseUrl = 'https://dfhhjceuynskmfhbkttn.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmaGhqY2V1eW5za21maGJrdHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUwMjQwMTYsImV4cCI6MjA0MDYwMDAxNn0.nrO5bOBk-QLtwmpDGsF-w8invjVCHN9H5YELDHd3xo4'

